// The safe bridge between the app window and the main process.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('cdbs', {
  pickCsv: () => ipcRenderer.invoke('pick-csv'),
  generateReport: () => ipcRenderer.invoke('generate-report'),
  onGenReportProgress: (cb) => ipcRenderer.on('genreport-progress', (e, d) => cb(d)),
  runAll: () => ipcRenderer.invoke('run-all'),
  stopAll: () => ipcRenderer.invoke('stop-all'),
  onRunAllProgress: (cb) => ipcRenderer.on('runall-progress', (e, d) => cb(d)),
  onRunallLive: (cb) => ipcRenderer.on('runall-live', (e, d) => cb(d)),
  onRunAllFinished: (cb) => ipcRenderer.on('runall-finished', (e, d) => cb(d)),
  morningGetSettings: () => ipcRenderer.invoke('morning-get-settings'),
  morningSaveSettings: (u) => ipcRenderer.invoke('morning-save-settings', u),
  fbAuthTest: () => ipcRenderer.invoke('fb-auth-test'),
  morningTestTelegram: () => ipcRenderer.invoke('morning-test-telegram'),
  morningRunNow: () => ipcRenderer.invoke('morning-run-now'),
  morningStop: () => ipcRenderer.invoke('morning-stop'),
  runFile: (items) => ipcRenderer.invoke('run-file', items),
  checkOne: (p) => ipcRenderer.invoke('check-one', p),
  onCheckOneProgress: (cb) => ipcRenderer.on('checkone-progress', (e, d) => cb(d)),
  supplyCode: (code) => ipcRenderer.invoke('supply-code', code),
  onProdaLight: (cb) => ipcRenderer.on('proda-light', (e, d) => cb(d)),
  findNumber: (p) => ipcRenderer.invoke('find-number', p),
  pickFindCsv: () => ipcRenderer.invoke('pick-find-csv'),
  findFile: (items) => ipcRenderer.invoke('find-file', items),
  onFindProgress: (cb) => ipcRenderer.on('find-progress', (e, d) => cb(d)),
  onFindFinished: (cb) => ipcRenderer.on('find-finished', (e, d) => cb(d)),
  openRunLog: () => ipcRenderer.invoke('open-run-log'),
  actionGet: () => ipcRenderer.invoke('action-get'),
  actionTick: (p) => ipcRenderer.invoke('action-tick', p),
  actionDelete: (p) => ipcRenderer.invoke('action-delete', p),
  actionAdd: (p) => ipcRenderer.invoke('action-add', p),
  actionStage: (p) => ipcRenderer.invoke('action-stage', p),
  denticareSteps: (p) => ipcRenderer.invoke('denticare-steps', p),
  actionNote: (p) => ipcRenderer.invoke('action-note', p),
  actionViewsTag: (p) => ipcRenderer.invoke('action-views-tag', p),
  viewsConfigSet: (p) => ipcRenderer.invoke('views-config-set', p),
  actionDue: (p) => ipcRenderer.invoke('action-due', p),
  reactOutcome: (p) => ipcRenderer.invoke('react-outcome', p),
  reactWriteNote: (p) => ipcRenderer.invoke('react-write-note', p),
  reactSendSms: (p) => ipcRenderer.invoke('react-send-sms', p),
  reactSmsTemplate: (p) => ipcRenderer.invoke('react-sms-template', p),
  reactOpenPatient: (p) => ipcRenderer.invoke('react-open-patient', p),
  reactNoteCommit: (p) => ipcRenderer.invoke('react-note-commit', p),
  reactNoteDel: (p) => ipcRenderer.invoke('react-note-del', p),
  reactCdbsCheck: (p) => ipcRenderer.invoke('reactcdbs-check', p),
  patientStateMap: () => ipcRenderer.invoke('patient-state-map'),
  engineBusy: () => ipcRenderer.invoke('engine-busy'),
  stopEverything: () => ipcRenderer.invoke('stop-everything'),
  workerGet: () => ipcRenderer.invoke('worker-get'),
  workerSet: (p) => ipcRenderer.invoke('worker-set', p),
  cloudHealth: () => ipcRenderer.invoke('cloud-health'),
  actionPinNote: (p) => ipcRenderer.invoke('action-pin-note', p),
  actionPark: (p) => ipcRenderer.invoke('action-park', p),
  noteRetry: (p) => ipcRenderer.invoke('note-retry', p),
  autoRunAll: (p) => ipcRenderer.invoke('auto-run-all', p),
  runallSched: (p) => ipcRenderer.invoke('runall-sched', p),
  fleetLastruns: () => ipcRenderer.invoke('fleet-lastruns'),
  runHistory: () => ipcRenderer.invoke('run-history'),
  debugFeedLink: () => ipcRenderer.invoke('debug-feed-link'),
  fleetPublish: () => ipcRenderer.invoke('fleet-publish'),
  fleetRole: () => ipcRenderer.invoke('fleet-role'),
  debugPrompt: () => ipcRenderer.invoke('debug-prompt'),
  appBuild: () => ipcRenderer.invoke('app-build'),
  debugTemplateGet: () => ipcRenderer.invoke('debug-template-get'),
  debugTemplateSave: (p) => ipcRenderer.invoke('debug-template-save', p),
  autoGet: () => ipcRenderer.invoke('auto-get'),
  shareHtmlGet: () => ipcRenderer.invoke('share-html-get'),
  shareHtmlSave: () => ipcRenderer.invoke('share-html-save'),
  autoSave: (p) => ipcRenderer.invoke('auto-save', p),
  autoRun: (p) => ipcRenderer.invoke('auto-run', p),
  birthdayTest: (p) => ipcRenderer.invoke('birthday-test', p),
  statusGet: () => ipcRenderer.invoke('status-get'),
  errorsGet: () => ipcRenderer.invoke('errors-get'),
  onRunStatus: (cb) => ipcRenderer.on('run-status', (e, d) => cb(d)),
  pillLogin: (p) => ipcRenderer.invoke('pill-login', p),
  logReport: () => ipcRenderer.invoke('log-report'),
  openExternal: (u) => ipcRenderer.invoke('open-external', u),
  diagCapture: (p) => ipcRenderer.invoke('diag-capture', p),
  diagWindow: (p) => ipcRenderer.invoke('diag-window', p),
  diagVitals: () => ipcRenderer.invoke('diag-vitals'),
  diagRecord: (p) => ipcRenderer.invoke('diag-record', p),
  onActionsChanged: (cb) => ipcRenderer.on('actions-changed', (e, d) => cb(d)),
  startRun: (items) => ipcRenderer.invoke('start-run', items),
  stopRun: () => ipcRenderer.invoke('stop-run'),
  openPrinciple: () => ipcRenderer.invoke('open-principle'),
  openFile: (file) => ipcRenderer.invoke('open-file', file),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  checkLogin: (openIfNeeded) => ipcRenderer.invoke('check-login', openIfNeeded),
  inspectFields: () => ipcRenderer.invoke('inspect-fields'),
  snapshotMedicare: (payload) => ipcRenderer.invoke('snapshot-medicare', payload),
  preportStart: () => ipcRenderer.invoke('preport-start'),
  preportMark: (label) => ipcRenderer.invoke('preport-mark', label),
  preportStop: () => ipcRenderer.invoke('preport-stop'),
  preportOpenFolder: () => ipcRenderer.invoke('preport-open-folder'),
  onPreportEvent: (cb) => ipcRenderer.on('preport-event', (e,d)=>cb(d)),
  onProdaEvent: (cb) => ipcRenderer.on('proda-event', (e,d)=>cb(d)),
  prodaOpen: () => ipcRenderer.invoke('proda-open'),
  prodaStartCapture: () => ipcRenderer.invoke('proda-start-capture'),
  prodaMark: (label) => ipcRenderer.invoke('proda-mark', label),
  prodaStopCapture: () => ipcRenderer.invoke('proda-stop-capture'),
  prodaStatus: () => ipcRenderer.invoke('proda-status'),
  checkBalances: (payload) => ipcRenderer.invoke('check-balances', payload),
  stopBalances: () => ipcRenderer.invoke('stop-balances'),
  onBalanceProgress: (cb) => ipcRenderer.on('balance-progress', (e,d)=>cb(d)),
  onBalancePaused: (cb) => ipcRenderer.on('balance-paused', (e,d)=>cb(d)),
  onBalanceFinished: (cb) => ipcRenderer.on('balance-finished', (e,d)=>cb(d)),
  collectMedicare: (payload) => ipcRenderer.invoke('collect-medicare', payload),
  stopCollect: () => ipcRenderer.invoke('stop-collect'),
  onCollectProgress: (cb) => ipcRenderer.on('collect-progress', (e, d) => cb(d)),
  onCollectFinished: (cb) => ipcRenderer.on('collect-finished', (e, d) => cb(d)),
  onLoginStatus: (cb) => ipcRenderer.on('login-status', (e, data) => cb(data)),
  onProgress: (cb) => ipcRenderer.on('run-progress', (e, data) => cb(data)),
  onFinished: (cb) => ipcRenderer.on('run-finished', (e, data) => cb(data)),
});
