// =====================================================================
//  principle-capture.js
//
//  Records how Principle's custom report screen works, so the report can
//  later be generated by the app instead of exported by hand.
//
//  Deliberately kept SEPARATE from principle-engine.js, because that file is
//  shared byte-for-byte with the Command Center app and shouldn't drift.
//  This module attaches to the same logged-in Principle session without
//  modifying the engine at all.
//
//  It only watches. Nothing is clicked, submitted or downloaded on your
//  behalf, and every digit is replaced with # before anything is saved.
// =====================================================================

const { BrowserWindow, session, app, Menu, dialog } = require('electron');
const path = require('path');
const fs = require('fs');

// Fallback only — this app's Principle window lives in persist:principle-admin
// (set by main.js). The download hook below prefers the session of the window
// itself, so this constant can never put the listener on the wrong session.
const PARTITION = 'persist:principle-admin';

let capturing = false;
let pages = [];
let downloads = [];
let listenersAttached = false;
let navHooked = new WeakSet();
let notify = () => {};

// main.js gives us a way to tell the app window what's happening, since the
// Principle window will be in front while you work.
function setNotifier(fn) { notify = typeof fn === 'function' ? fn : () => {}; }

// ---------------------------------------------------------------------
// Finding the Principle window that the engine already opened
// ---------------------------------------------------------------------
function principleWindow() {
  return BrowserWindow.getAllWindows().find(w => {
    try {
      return !w.isDestroyed() && /principle\.dental/i.test(w.webContents.getURL() || '');
    } catch (e) {
      return false;
    }
  }) || null;
}

// ---------------------------------------------------------------------
// Redaction
// ---------------------------------------------------------------------
const maskDigits = (t) => String(t || '').replace(/\d/g, '#');


// IMPORTANT: Electron allows only ONE webRequest listener per event per
// session. principle-engine.js already uses those on this session to learn
// Principle's patient search, so registering our own here would silently
// disable it. We therefore do NOT touch webRequest at all — page snapshots
// and the download hook (a normal event, which can have many listeners)
// give us everything this feature needs.
function attachListeners() {
  if (listenersAttached) return;
  // Use the session of the Principle window that's actually open, so the
  // download hook is guaranteed to be on the right one. The partition name
  // is only a fallback for the (unlikely) case of no window yet.
  const win = principleWindow();
  const ses = win ? win.webContents.session : session.fromPartition(PARTITION);
  listenersAttached = true;

  // A dry run of the real thing: the report download is caught and saved into
  // this program's own folder rather than Downloads, so you can confirm it's
  // the right file — and so the automatic version later has nothing to fish
  // out of Downloads or guess at.
  ses.on('will-download', (event, item) => {
    if (!capturing) return;

    const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const safeName = String(item.getFilename() || 'report.csv').replace(/[^A-Za-z0-9._-]/g, '_');
    const saveTo = path.join(reportsFolder(), `${stamp}__${safeName}`);

    const record = {
      time: new Date().toISOString(),
      filename: item.getFilename(),
      mimeType: item.getMimeType(),
      url: maskDigits(item.getURL()).slice(0, 400),
      totalBytes: item.getTotalBytes(),
      savedTo: saveTo,
      state: 'started',
    };
    downloads.push(record);

    try {
      item.setSavePath(saveTo);
    } catch (e) {
      record.state = 'could-not-set-path';
      return;
    }

    item.once('done', (e, state) => {
      record.state = state;
      if (state === 'completed') {
        try {
          const text = fs.readFileSync(saveTo, 'utf8');
          const lines = text.split(/\r?\n/).filter(l => l.trim());
          record.rowCount = Math.max(0, lines.length - 1);
          record.headerRow = (lines[0] || '').slice(0, 600);
          record.hasPatientLink = /link/i.test(lines[0] || '');
        } catch (err) {
          record.readError = String(err);
        }
      }
    });
  });
}

// ---------------------------------------------------------------------
// Page structure — labels and value shapes only
// ---------------------------------------------------------------------
function structureScript() {
  return `(() => {
    const visible = el => el && el.offsetParent !== null && el.getClientRects().length > 0;
    const clean = t => String(t || '').trim().replace(/\\s+/g, ' ');

    const shape = (raw) => {
      const t = clean(raw);
      if (!t) return 'empty';
      const digits = (t.match(/\\d/g) || []).length;
      const letters = (t.match(/[A-Za-z]/g) || []).length;
      if (digits && !letters) return digits + ' digits';
      if (digits && letters) return digits + ' digits + ' + letters + ' letters';
      return letters + ' letters';
    };

    const labelFor = (el) => {
      const aria = el.getAttribute('aria-label') || el.getAttribute('placeholder');
      if (aria) return clean(aria);
      const id = el.getAttribute('id');
      if (id) {
        try {
          const lab = document.querySelector('label[for="' + id + '"]');
          if (lab) return clean(lab.innerText);
        } catch (e) { /* ignore */ }
      }
      const field = el.closest('mat-form-field, .field, .form-field, div');
      if (field) {
        const lab = field.querySelector('label, mat-label, .label');
        if (lab) return clean(lab.innerText);
      }
      return '';
    };

    return {
      url: location.href,
      title: clean(document.title),
      headings: [...document.querySelectorAll('h1, h2, h3, h4, mat-card-title')].filter(visible)
        .map(h => clean(h.innerText)).filter(Boolean).slice(0, 30),
      inputs: [...document.querySelectorAll('input, select, textarea, mat-select')].filter(visible).map(el => ({
        label: labelFor(el).slice(0, 70),
        tag: el.tagName,
        type: el.getAttribute('type') || '',
        name: el.getAttribute('name') || el.getAttribute('formcontrolname') || '',
        id: (el.getAttribute('id') || '').slice(0, 60),
        cls: (el.className || '').toString().slice(0, 90),
        valueShape: shape(el.value || el.innerText),
      })).slice(0, 50),
      buttons: [...document.querySelectorAll('button, [role=button], a.mat-mdc-button, input[type=submit]')]
        .filter(visible)
        .map(b => ({
          text: clean(b.innerText || b.value || b.getAttribute('aria-label')).slice(0, 60),
          id: (b.getAttribute('id') || '').slice(0, 60),
          cls: (b.className || '').toString().slice(0, 90),
          disabled: !!b.disabled,
        })).filter(b => b.text).slice(0, 50),
      tableHeaders: [...document.querySelectorAll('table')].filter(visible).slice(0, 4)
        .map(t => [...t.querySelectorAll('th')].map(th => clean(th.innerText)).slice(0, 15)),
      maskedText: clean(document.body ? (document.body.innerText || '') : '')
        .replace(/\\d/g, '#').slice(0, 2500),
    };
  })()`;
}

async function snapshot(label) {
  const win = principleWindow();
  if (!win) return null;
  let data;
  try {
    data = await win.webContents.executeJavaScript(structureScript(), true);
  } catch (e) {
    data = { error: String(e) };
  }
  const entry = { label: label || '', at: new Date().toISOString(), ...data };
  pages.push(entry);
  return entry;
}

// ---------------------------------------------------------------------
// Capture control
// ---------------------------------------------------------------------
// The Principle window sits in front while you're using it, so the recording
// controls go into ITS menu bar. Reaching back to the app window mid-recording
// is exactly the sort of fiddling this is meant to avoid.
function applyCaptureMenu(win) {
  if (!win || win.isDestroyed()) return;
  const menu = Menu.buildFromTemplate([
    {
      label: 'Recording',
      submenu: [
        {
          label: 'Mark this screen',
          accelerator: 'CmdOrCtrl+M',
          click: async () => {
            const snap = await snapshot('marked by hand');
            notify({ type: 'marked', title: snap && snap.title });
          },
        },
        { type: 'separator' },
        {
          label: 'Stop and save',
          click: async () => {
            const res = await stop();
            clearCaptureMenu(win);
            notify({ type: 'stopped', result: res });
            if (res && res.ok) {
              dialog.showMessageBox(win, {
                type: 'info',
                title: 'Recording saved',
                message: `Saved ${res.pageCount} screen${res.pageCount === 1 ? '' : 's'}.`,
                detail: res.downloadCount
                  ? 'The report CSV was saved into the program\'s own folder. Switch back to the app window for the details.'
                  : 'No report download was seen. Switch back to the app window for the details.',
                buttons: ['OK'],
              });
            }
          },
        },
      ],
    },
    { role: 'editMenu' },
    { label: 'Reload', role: 'reload' },
  ]);
  win.setMenu(menu);
  win.setMenuBarVisibility(true);
}

function clearCaptureMenu(win) {
  if (!win || win.isDestroyed()) return;
  try { win.setMenu(null); } catch (e) { /* ignore */ }
}

function start() {
  attachListeners();
  capturing = true;
  pages = [];
  downloads = [];

  const win = principleWindow();
  if (win) applyCaptureMenu(win);
  if (win && !navHooked.has(win.webContents)) {
    navHooked.add(win.webContents);
    win.webContents.on('did-finish-load', () => {
      if (capturing) setTimeout(() => snapshot('page loaded'), 1200);
    });
    win.webContents.on('did-navigate-in-page', () => {
      if (capturing) setTimeout(() => snapshot('screen changed'), 1200);
    });
  }
  setTimeout(() => snapshot('recording started'), 500);
  return { ok: true, windowFound: !!win };
}

// Reports are kept in this program's own folder, not Downloads.
function reportsFolder() {
  const dir = path.join(app.getPath('userData'), 'reports');
  try { fs.mkdirSync(dir, { recursive: true }); } catch (e) { /* ignore */ }
  return dir;
}

function filePath() {
  return path.join(app.getPath('documents'), 'principle-report-capture.json');
}

async function stop() {
  await snapshot('recording stopped');
  capturing = false;

  const payload = {
    capturedAt: new Date().toISOString(),
    note: 'Digits replaced with #, sensitive headers redacted. Downloaded reports were saved into this program\'s own folder, NOT into this file — only the column headers are recorded here.',
    reportsSavedIn: reportsFolder(),
    downloads,
    pageCount: pages.length,
    downloadCount: downloads.length,
    pages,
  };

  const file = filePath();
  try {
    fs.writeFileSync(file, JSON.stringify(payload, null, 2), 'utf8');
    return { ok: true, file, pageCount: pages.length,
             downloadCount: downloads.length, downloads };
  } catch (e) {
    return { ok: false, error: String(e) };
  }
}

function isCapturing() { return capturing; }

module.exports = { start, stop, snapshot, isCapturing, filePath, principleWindow, reportsFolder, setNotifier, applyCaptureMenu };
